CREATE TABLE tx_evangtermine_domain_model_event
(
	id int(11) unsigned DEFAULT 0 NOT NULL,
	start int(11) unsigned DEFAULT 0 NOT NULL,
	end int(11) unsigned DEFAULT 0 NOT NULL,
	mode varchar(255) DEFAULT '' NOT NULL,
	subtitle varchar(255) DEFAULT '' NOT NULL,
	datum1 varchar(255) DEFAULT '' NOT NULL,
	datum2 varchar(255) DEFAULT '' NOT NULL,
	monthbar varchar(255) DEFAULT '' NOT NULL,
	allday int(4) unsigned DEFAULT 0 NOT NULL,
	event_id int(11) unsigned DEFAULT 0 NOT NULL,
	event_inputmask_id int(11) unsigned DEFAULT 0 NOT NULL,
	title varchar(255) DEFAULT '' NOT NULL,
	categories varchar(255) DEFAULT '' NOT NULL,
	people varchar(255) DEFAULT '' NOT NULL,
	short_description text,
	long_description text,
	link varchar(255) DEFAULT '' NOT NULL,
	event_kat varchar(255) DEFAULT '' NOT NULL,
	event_kat2 varchar(255) DEFAULT '' NOT NULL,
	email varchar(255) DEFAULT '' NOT NULL,
	event_person_id int(11) unsigned DEFAULT 0 NOT NULL,
	event_place_id int(11) unsigned DEFAULT 0 NOT NULL,
	region varchar(255) DEFAULT '' NOT NULL,
	event_subregion_id varchar(255) DEFAULT '' NOT NULL,
	event_region2_id varchar(128) DEFAULT '' NOT NULL,
	event_region3_id varchar(128) DEFAULT '' NOT NULL,
	event_profession_id varchar(255) DEFAULT '' NOT NULL,
	event_music_kat_id varchar(255) DEFAULT '' NOT NULL,
	event_flag1 varchar(128) DEFAULT '' NOT NULL,
	textline1 text,
	textline2 text,
	textline3 text,
	textline4 text,
	textline5 text,
	textline6 text,
	textline7 text,
	textline8 text,
	textbox1 text,
	textbox2 text,
	textbox3 text,
	event_number1 varchar(255) DEFAULT '' NOT NULL,
	event_number2 varchar(255) DEFAULT '' NOT NULL,
	event_number3 varchar(255) DEFAULT '' NOT NULL,
	event_menue1 varchar(255) DEFAULT '' NOT NULL,
	event_menue2 varchar(255) DEFAULT '' NOT NULL,
	event_yesno1 varchar(32) DEFAULT '' NOT NULL,
	event_yesno2 varchar(32) DEFAULT '' NOT NULL,
	event_yesno3 varchar(32) DEFAULT '' NOT NULL,
	event_destination varchar(255) DEFAULT '' NOT NULL,
	event_status varchar(32) DEFAULT '' NOT NULL,
	feedback_id int(11) unsigned DEFAULT 0 NOT NULL,
	highlight int(4) unsigned DEFAULT 0 NOT NULL,
	event_coursetype varchar(255) DEFAULT '' NOT NULL,
	event_care varchar(255) DEFAULT '' NOT NULL,
	event_kollekte varchar(255) DEFAULT '' NOT NULL,
	event_statistik varchar(255) DEFAULT '' NOT NULL,
	event_external_id int(11) unsigned DEFAULT 0 NOT NULL,
	event_access varchar(255) DEFAULT '' NOT NULL,
	event_lang varchar(32) DEFAULT '' NOT NULL,
	event_user_id int(11) unsigned DEFAULT 0 NOT NULL,
	image varchar(255) DEFAULT '' NOT NULL,
	caption varchar(255) DEFAULT '' NOT NULL,
	event_modified varchar(32) DEFAULT '' NOT NULL,
	event_koll_descr text,
	poll_id varchar(255) DEFAULT '' NOT NULL,
	webform_linkname varchar(255) DEFAULT '' NOT NULL,
	inputmask_name varchar(255) DEFAULT '' NOT NULL,
	place_id int(11) unsigned DEFAULT 0 NOT NULL,
	place_name varchar(255) DEFAULT '' NOT NULL,
	place_street_nr varchar(255) DEFAULT '' NOT NULL,
	place_zip varchar(8) DEFAULT '' NOT NULL,
	place_city varchar(255) DEFAULT '' NOT NULL,
	place_info text,
	place_hidden varchar(255) DEFAULT '' NOT NULL,
	place_image varchar(255) DEFAULT '' NOT NULL,
	place_image_caption varchar(255) DEFAULT '' NOT NULL,
	place_position int(11) unsigned DEFAULT 0 NOT NULL,
	place_kat varchar(255) DEFAULT '' NOT NULL,
	place_open text,
	place_equip varchar(255) DEFAULT '' NOT NULL,
	place_equiptext text,
	place_region varchar(128) DEFAULT '' NOT NULL,
	lat varchar(64) DEFAULT '' NOT NULL,
	lon varchar(64) DEFAULT '' NOT NULL,
	person_name varchar(255) DEFAULT '' NOT NULL,
	person_email varchar(255) DEFAULT '' NOT NULL,
	person_contact varchar(255) DEFAULT '' NOT NULL,
	person_position int(11) unsigned DEFAULT 0 NOT NULL,
	person_surname varchar(128) DEFAULT '' NOT NULL,
	user_id int(11) unsigned DEFAULT 0 NOT NULL,
	user_realname varchar(255) DEFAULT '' NOT NULL,
	user_description varchar(255) DEFAULT '' NOT NULL,
	user_street_nr varchar(255) DEFAULT '' NOT NULL,
	user_zip varchar(8) DEFAULT '' NOT NULL,
	user_city varchar(255) DEFAULT '' NOT NULL,
	user_email varchar(255) DEFAULT '' NOT NULL,
	user_url varchar(255) DEFAULT '' NOT NULL,
	user_contact varchar(255) DEFAULT '' NOT NULL,
	user_intdata varchar(255) DEFAULT '' NOT NULL,
	user_image varchar(255) DEFAULT '' NOT NULL,
	liturg_bez varchar(255) DEFAULT '' NOT NULL,
	channels varchar(255) DEFAULT '' NOT NULL,
	attributes text,
	slug varchar(255) DEFAULT '' NOT NULL,
    hash varchar(40) DEFAULT '' NOT NULL,

	index index_start (start),
	index index_end (end),
	index index_title (title),
	index index_categories (categories),
	index index_people (people),
	index index_region (region),
	index index_highlight (highlight),
	index index_event_user_id (event_user_id),
	index index_place_id (place_id),
	index index_place_zip (place_zip),
	index index_place_city (place_city),
	index index_slug (slug),
    index index_id (id)
);

